apiVersion: v1
kind: Service
metadata:
  name: fe-ciickd-pc
  namespace: {{ .Values.namespace }}
  labels: {{ include "fe-ciickd-pc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector: {{ include "fe-ciickd-pc.selectorLabels" . | nindent 4 }}
